[package]
name = "rethdb-reader"
description = "A simple library for reading data through Reth's DB abstractions."
version = "0.1.0"
edition = "2021"

[lib]
name = "rethdbreader"
crate-type = ["cdylib"]

[dependencies]
reth = { git = "https://github.com/paradigmxyz/reth.git" }
serde = "1.0.190"
serde_json = "1.0.107"
anyhow = "1.0.75"
